### ISSUE TITLE
Weirdness with fonts

### ISSUE THREAD

**Issue by Hardmath123** [nathan/gistogram#1]
(Terminal - Monaco 12pt.)

![screen shot 2015-02-13 at 7 07 23 pm](https://cloud.githubusercontent.com/assets/5202416/6198411/d9503062-b3b3-11e4-826b-dffc5718cb70.png)

Suggestion: use ANSI terminal background colors instead of the block character, where supported. Those won't leave spaces between cells, though you won't be able to get fractions of a cell.

**Comment by nathan** [comment]
Ew, yeah. Fractional cells are nice, but that is very not pretty.

**Comment by nathan** [comment]
There are now normal (colored) and `--fancy` (block-ed) modes.
